### ISSUE TITLE
The variable '$myPackages' cannot be retrieved because it has not been set.

### ISSUE THREAD

**Issue by haugsten** [Epinova/epinova-dxp-deployment#216]
I get the following error deploying to preproduction after deploy to integration.
DXP environment: Linux

2022-03-30T13:09:29.8038231Z cms package already exist in container.
2022-03-30T13:09:29.8041074Z 
2022-03-30T13:09:29.8976302Z ##[error][91mInvalidOperation: [0m/home/vsts/work/_tasks/DxpDeployNuGetPackage_2bc993e5-c27c-4a24-aeaf-0fc403debc8d/2.2.16/DeployNuGetPackage.ps1:98
[96mLine |
[96m  98 | [0m             DeploymentPackage  = [96m$myPackages[0m
[96m     | [91m                                  ~~~~~~~~~~~
[91m[96m     | [91mThe variable '$myPackages' cannot be retrieved because it has
[96m     | [91mnot been set.
[0m

**Comment by ovelartelius** [comment]
Hi @haugsten 
I will look into the problem ASAP. Getting back to you....

**Comment by ovelartelius** [comment]
Hi again @haugsten 
I have released a update where $myPackages is init... v2.2.15. The DeployNuGetPackage task is in v2.2.17
![image](https://user-images.githubusercontent.com/4722784/161066271-27eb1e28-410c-4f34-9935-e926cddb077d.png)

I can see that the message also contain "cms package already exist in container.". So the problem in Linux environment is that it can not overwrite the file on disc. And since The integration deploy uploaded the same file I suspect and then the error is thrown when upload the same filename in prep. I will look into this and see if I can find a solution where I rename the package so that is not a problem. Will get back to you..

**Comment by ovelartelius** [comment]
Hi @haugsten 
Now we have solved the issue. v2.2.16 is released and we have verified that it works in our environment. We manage to get the same error so we know that it works now. 
Have a good evening!

**Comment by haugsten** [comment]
Great, thank you very much!
