### ISSUE TITLE
Tasks aren't available within Azure DevOps releases anymore

### ISSUE THREAD

**Issue by JayWilk** [Epinova/epinova-dxp-deployment#232]
- Install the latest version of this extension into your Azure DevOps organisation from the Visual Studio Marketplace (time of writing this is 2.2.20)
- Observe that the extension has successfully installed by going to Organization Settings -> Extensions in DevOps 
- Go to your Azure DevOps instance and go to create a new release pipeline
- Next to 'Select a template' - search for any of the Epinova tasks and none are showing in the results:
![2022-09-07 11_55_16-](https://user-images.githubusercontent.com/4315917/188861801-e3beec73-67c4-46ce-83a5-b31648a4c871.png)

**Additional observation**
The tasks do show when configuring a Pipeline build - but they are no longer available for release pipelines.

![2022-09-07 11_58_12-](https://user-images.githubusercontent.com/4315917/188862254-a7abe858-daa9-4980-8584-e37f74acd93a.png)

**Comment by ovelartelius** [comment]
Hi @JayWilk 
Thanks for info! I will have a look...

**Comment by ovelartelius** [comment]
Hi @JayWilk 
If I look on your first image you are searching for a release pipeline template. We have never created a template. So if you click on a "stage" and then click "Add task". Then do should be able to search for the Epinova tasks. And if you want to find all of them you can search for "DXP" since all tasks are found in that case.
![image](https://user-images.githubusercontent.com/4722784/189087172-94cbbf0b-8e8c-4edd-8079-a372588743cd.png)
I hope the image above here show where you should search for tasks.

**Comment by ovelartelius** [comment]
Hi @JayWilk. Have you had time to see if you can see the tasks?
