### ISSUE TITLE
Non-Descriptive 'We found ERRORS' Error Messages

### ISSUE THREAD

**Issue by OnePiece-GoingMerry** [Epinova/epinova-dxp-deployment#326]
When the dxp smoke test fails, we currently receive non-descriptive error messages such as `We found ERRORS`. This does not accurately tell us the cause of the smoke test failure and implies that Dxp might be the cause however there are cases when the code being deployed to Dxp are the cause of the smoke test failing. In order to successfully and accurately pinpoint the cause of failures, it would highly useful if the error messages are more detailed and contains the actual cause of the errors.

**Comment by ovelartelius** [comment]
Hi @OnePiece-GoingMerry. Sorry for very late reply. Is it possible that you can show what happends eariler from the log. 
I asking because the script should give you more information then this. And to figure out what problem we have in the script I need some more information. If you don´t want to paste the log here you can send the log directly to my email ove.lartelius@epinova.se
Regards
Ove

**Comment by ovelartelius** [comment]
Hi @OnePiece-GoingMerry 
I assume that it works for you. If not you can always create a new issue.
Regards
Ove
